### ISSUE TITLE
Im getting errors  

### ISSUE THREAD

**Issue by Imnthg** [TheLastAirbendr/mysql-for-termux#2]
![Screenshot_2021-12-26-21-21-21-990_com.termux.jpg](https://user-images.githubusercontent.com/93459733/147413378-3511398a-8a50-4b48-af73-ee7a52a6dd38.jpg)

**Comment by ItsK1tty** [comment]
can confirm

**Comment by Imnthg** [comment]
Can u explain me in detail

**Comment by ItsK1tty** [comment]
it's not like there's something to explain, i just encountered the same issue as you did

**Comment by Imnthg** [comment]
Then how can I slove this problem...u said sonwways I tried that too..now?

**Comment by anay-p** [comment]
It seems the Google Play version of Termux will not be receiving any more updates, so please download and install the official release of Termux from F-Droid [here](https://f-droid.org/packages/com.termux/). I have tried and it works. If you encounter any further issues, feel free to mention them here.
Edit: You can read more about this [here](https://github.com/termux/termux-app#google-play-store-deprecated)

**Comment by anay-p** [comment]
Also, if the issue is resolved, do let me know so that I can close this issue.

**Comment by ItsK1tty** [comment]
Resolved for me, thank you.
